### ISSUE TITLE
Error when creating authentication

### ISSUE THREAD

**Issue by drewubaldeayson** [salkuadrat/fxendit#4]
Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by salkuadrat** [comment]
Hi @drewubaldeayson 

You can use the new updated version (0.0.3).
The dependencies for xendit sdk & cardinal mobile sdk has been updated to the newest version.

**Comment by drewubaldeayson** [comment]
@salkuadrat  thank you sir!
